spring.application.name=nutrivision-backend
spring.config.import=optional:file:.env[.properties]

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Database
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
server.address=0.0.0.0